version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - JWT_USERNAME=user
      - JWT_PASSWORD=password
      - JWT_SECRET=defaultjwtsecret
      - MONGODB_URI=mongodb://mongo:27017/phone-number-management
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - /usr/src/app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
